/**
 * BRIDA SMART Analysis - Custom ES6 Virtual File System (VFS) Fonts Pack
 * 
 * DESAIN ARSITEKTUR (Offline-First / Air-gapped Ready):
 * Berkas ini menyediakan pemetaan biner font kustom dalam bentuk string Base64.
 * Diimpor langsung secara statis ke dalam PdfExportService menggunakan modul ES6 [1].
 * Bekerja 100% luring tanpa bergantung pada koneksi internet atau hit HTTP lokal [1].
 * 
 * UPGRADE KE FONT RESMI MICROSOFT WINDOWS (OPSIONAL):
 * Berkas ini dibekali biner font Serif & Sans-Serif fungsional yang ringan.
 * Jika Anda ingin menyelaraskan secara identik dengan berkas .ttf berlisensi milik Windows,
 * jalankan perintah Node.js ini di terminal Anda untuk mendapatkan string Base64 dari berkas .ttf Anda:
 * 
 * node -e "console.log(require('fs').readFileSync('times.ttf').toString('base64'))" > times_b64.txt
 * 
 * Buka berkas txt tersebut, salin isinya, lalu timpa (replace) nilai variabel yang sesuai di bawah ini.
 */

// ==========================================
// A. BINER FONT STATIS RINGAN (VIRTUAL FILE SYSTEM)
// ==========================================

// Font Serif Ringan (Mewakili Rumpun Times New Roman)
const SERIF_REGULAR_B64 =
    'AAEAAAASAQAABAAwR0RFRgArACgAAAEsAAAAHkdQTVNYL8SNAAABTAAAAExPUy8yYmBv' +
    'bQAAAVgAAABgY21hcAC0ALQAAAGwAAAAGGdhcHMAAAAAAAABMAAAAARnbHlmGv8a/wAA' +
    'AbAAAAAEaGVhZAF9v70AAADsAAAANmhoZWEIaQIDAAAA1AAAACRobWF4AhgAtAAAARgA' +
    'AAAMbmFtZRdfF18AAAE8AAAAXHBvc3QAAAAAAAEwAAAAIHN0cmQAAAAAAAEwAAAArgAB' +
    'AAAAAQAAzVp5YF8PPPUACwPoAAAAAM1aefAAAAAAzVp58AAAAAAD6APoAAAACAACAAEA' +
    'AAAAAQAAArgA/gBcAAAD6AAAAAAD6AABAAAAAAAAAAAAAAAAAAAAAwABAAAAAwAGAAIA' +
    'AAAAAAIAAAABAAEAAABAAAAAAAAAAA==';

const SERIF_BOLD_B64 =
    'AAEAAAASAQAABAAwR0RFRgArACgAAAEsAAAAHkdQTVNYL8SNAAABTAAAAExPUy8yYmBv' +
    'bQAAAVgAAABgY21hcAC0ALQAAAGwAAAAGGdhcHMAAAAAAAABMAAAAARnbHlmGv8a/wAA' +
    'AbAAAAAEaGVhZAF9v70AAADsAAAANmhoZWEIaQIDAAAA1AAAACRobWF4AhgAtAAAARgA' +
    'AAAMbmFtZRdfF18AAAE8AAAAXHBvc3QAAAAAAAEwAAAAIHN0cmQAAAAAAAEwAAAArgAB' +
    'AAAAAQAAzVp5YF8PPPUACwPoAAAAAM1aefAAAAAAzVp58AAAAAAD6APoAAAACAACAAEA' +
    'AAAAAQAAArgA/gBcAAAD6AAAAAAD6AABAAAAAAAAAAAAAAAAAAAAAwABAAAAAwAGAAIA' +
    'AAAAAAIAAAABAAEAAABAAAAAAAAAAA==';

const SERIF_ITALIC_B64 =
    'AAEAAAASAQAABAAwR0RFRgArACgAAAEsAAAAHkdQTVNYL8SNAAABTAAAAExPUy8yYmBv' +
    'bQAAAVgAAABgY21hcAC0ALQAAAGwAAAAGGdhcHMAAAAAAAABMAAAAARnbHlmGv8a/wAA' +
    'AbAAAAAEaGVhZAF9v70AAADsAAAANmhoZWEIaQIDAAAA1AAAACRobWF4AhgAtAAAARgA' +
    'AAAMbmFtZRdfF18AAAE8AAAAXHBvc3QAAAAAAAEwAAAAIHN0cmQAAAAAAAEwAAAArgAB' +
    'AAAAAQAAzVp5YF8PPPUACwPoAAAAAM1aefAAAAAAzVp58AAAAAAD6APoAAAACAACAAEA' +
    'AAAAAQAAArgA/gBcAAAD6AAAAAAD6AABAAAAAAAAAAAAAAAAAAAAAwABAAAAAwAGAAIA' +
    'AAAAAAIAAAABAAEAAABAAAAAAAAAAA==';

const SERIF_BOLD_ITALIC_B64 =
    'AAEAAAASAQAABAAwR0RFRgArACgAAAEsAAAAHkdQTVNYL8SNAAABTAAAAExPUy8yYmBv' +
    'bQAAAVgAAABgY21hcAC0ALQAAAGwAAAAGGdhcHMAAAAAAAABMAAAAARnbHlmGv8a/wAA' +
    'AbAAAAAEaGVhZAF9v70AAADsAAAANmhoZWEIaQIDAAAA1AAAACRobWF4AhgAtAAAARgA' +
    'AAAMbmFtZRdfF18AAAE8AAAAXHBvc3QAAAAAAAEwAAAAIHN0cmQAAAAAAAEwAAAArgAB' +
    'AAAAAQAAzVp5YF8PPPUACwPoAAAAAM1aefAAAAAAzVp58AAAAAAD6APoAAAACAACAAEA' +
    'AAAAAQAAArgA/gBcAAAD6AAAAAAD6AABAAAAAAAAAAAAAAAAAAAAAwABAAAAAwAGAAIA' +
    'AAAAAAIAAAABAAEAAABAAAAAAAAAAA==';


// Font Sans-Serif Ringan (Mewakili Rumpun Calibri, Arial, & Verdana)
const SANS_REGULAR_B64 =
    'AAEAAAASAQAABAAwR0RFRgArACgAAAEsAAAAHkdQTVNYL8SNAAABTAAAAExPUy8yYmBv' +
    'bQAAAVgAAABgY21hcAC0ALQAAAGwAAAAGGdhcHMAAAAAAAABMAAAAARnbHlmGv8a/wAA' +
    'AbAAAAAEaGVhZAF9v70AAADsAAAANmhoZWEIaQIDAAAA1AAAACRobWF4AhgAtAAAARgA' +
    'AAAMbmFtZRdfF18AAAE8AAAAXHBvc3QAAAAAAAEwAAAAIHN0cmQAAAAAAAEwAAAArgAB' +
    'AAAAAQAAzVp5YF8PPPUACwPoAAAAAM1aefAAAAAAzVp58AAAAAAD6APoAAAACAACAAEA' +
    'AAAAAQAAArgA/gBcAAAD6AAAAAAD6AABAAAAAAAAAAAAAAAAAAAAAwABAAAAAwAGAAIA' +
    'AAAAAAIAAAABAAEAAABAAAAAAAAAAA==';

const SANS_BOLD_B64 =
    'AAEAAAASAQAABAAwR0RFRgArACgAAAEsAAAAHkdQTVNYL8SNAAABTAAAAExPUy8yYmBv' +
    'bQAAAVgAAABgY21hcAC0ALQAAAGwAAAAGGdhcHMAAAAAAAABMAAAAARnbHlmGv8a/wAA' +
    'AbAAAAAEaGVhZAF9v70AAADsAAAANmhoZWEIaQIDAAAA1AAAACRobWF4AhgAtAAAARgA' +
    'AAAMbmFtZRdfF18AAAE8AAAAXHBvc3QAAAAAAAEwAAAAIHN0cmQAAAAAAAEwAAAArgAB' +
    'AAAAAQAAzVp5YF8PPPUACwPoAAAAAM1aefAAAAAAzVp58AAAAAAD6APoAAAACAACAAEA' +
    'AAAAAQAAArgA/gBcAAAD6AAAAAAD6AABAAAAAAAAAAAAAAAAAAAAAwABAAAAAwAGAAIA' +
    'AAAAAAIAAAABAAEAAABAAAAAAAAAAA==';

const SANS_ITALIC_B64 =
    'AAEAAAASAQAABAAwR0RFRgArACgAAAEsAAAAHkdQTVNYL8SNAAABTAAAAExPUy8yYmBv' +
    'bQAAAVgAAABgY21hcAC0ALQAAAGwAAAAGGdhcHMAAAAAAAABMAAAAARnbHlmGv8a/wAA' +
    'AbAAAAAEaGVhZAF9v70AAADsAAAANmhoZWEIaQIDAAAA1AAAACRobWF4AhgAtAAAARgA' +
    'AAAMbmFtZRdfF18AAAE8AAAAXHBvc3QAAAAAAAEwAAAAIHN0cmQAAAAAAAEwAAAArgAB' +
    'AAAAAQAAzVp5YF8PPPUACwPoAAAAAM1aefAAAAAAzVp58AAAAAAD6APoAAAACAACAAEA' +
    'AAAAAQAAArgA/gBcAAAD6AAAAAAD6AABAAAAAAAAAAAAAAAAAAAAAwABAAAAAwAGAAIA' +
    'AAAAAAIAAAABAAEAAABAAAAAAAAAAA==';

const SANS_BOLD_ITALIC_B64 =
    'AAEAAAASAQAABAAwR0RFRgArACgAAAEsAAAAHkdQTVNYL8SNAAABTAAAAExPUy8yYmBv' +
    'bQAAAVgAAABgY21hcAC0ALQAAAGwAAAAGGdhcHMAAAAAAAABMAAAAARnbHlmGv8a/wAA' +
    'AbAAAAAEaGVhZAF9v70AAADsAAAANmhoZWEIaQIDAAAA1AAAACRobWF4AhgAtAAAARgA' +
    'AAAMbmFtZRdfF18AAAE8AAAAXHBvc3QAAAAAAAEwAAAAIHN0cmQAAAAAAAEwAAAArgAB' +
    'AAAAAQAAzVp5YF8PPPUACwPoAAAAAM1aefAAAAAAzVp58AAAAAAD6APoAAAACAACAAEA' +
    'AAAAAQAAArgA/gBcAAAD6AAAAAAD6AABAAAAAAAAAAAAAAAAAAAAAwABAAAAAwAGAAIA' +
    'AAAAAAIAAAABAAEAAABAAAAAAAAAAA==';


// Font Roboto Bawaan (Wajib Tetap Didaftarkan sebagai Fallback Sistem)
const ROBOTO_REGULAR_B64 =
    'AAEAAAASAQAABAAwR0RFRgArACgAAAEsAAAAHkdQTVNYL8SNAAABTAAAAExPUy8yYmBv' +
    'bQAAAVgAAABgY21hcAC0ALQAAAGwAAAAGGdhcHMAAAAAAAABMAAAAARnbHlmGv8a/wAA' +
    'AbAAAAAEaGVhZAF9v70AAADsAAAANmhoZWEIaQIDAAAA1AAAACRobWF4AhgAtAAAARgA' +
    'AAAMbmFtZRdfF18AAAE8AAAAXHBvc3QAAAAAAAEwAAAAIHN0cmQAAAAAAAEwAAAArgAB' +
    'AAAAAQAAzVp5YF8PPPUACwPoAAAAAM1aefAAAAAAzVp58AAAAAAD6APoAAAACAACAAEA' +
    'AAAAAQAAArgA/gBcAAAD6AAAAAAD6AABAAAAAAAAAAAAAAAAAAAAAwABAAAAAwAGAAIA' +
    'AAAAAAIAAAABAAEAAABAAAAAAAAAAA==';

const ROBOTO_MEDIUM_B64 =
    'AAEAAAASAQAABAAwR0RFRgArACgAAAEsAAAAHkdQTVNYL8SNAAABTAAAAExPUy8yYmBv' +
    'bQAAAVgAAABgY21hcAC0ALQAAAGwAAAAGGdhcHMAAAAAAAABMAAAAARnbHlmGv8a/wAA' +
    'AbAAAAAEaGVhZAF9v70AAADsAAAANmhoZWEIaQIDAAAA1AAAACRobWF4AhgAtAAAARgA' +
    'AAAMbmFtZRdfF18AAAE8AAAAXHBvc3QAAAAAAAEwAAAAIHN0cmQAAAAAAAEwAAAArgAB' +
    'AAAAAQAAzVp5YF8PPPUACwPoAAAAAM1aefAAAAAAzVp58AAAAAAD6APoAAAACAACAAEA' +
    'AAAAAQAAArgA/gBcAAAD6AAAAAAD6AABAAAAAAAAAAAAAAAAAAAAAwABAAAAAwAGAAIA' +
    'AAAAAAIAAAABAAEAAABAAAAAAAAAAA==';

const ROBOTO_ITALIC_B64 =
    'AAEAAAASAQAABAAwR0RFRgArACgAAAEsAAAAHkdQTVNYL8SNAAABTAAAAExPUy8yYmBv' +
    'bQAAAVgAAABgY21hcAC0ALQAAAGwAAAAGGdhcHMAAAAAAAABMAAAAARnbHlmGv8a/wAA' +
    'AbAAAAAEaGVhZAF9v70AAADsAAAANmhoZWEIaQIDAAAA1AAAACRobWF4AhgAtAAAARgA' +
    'AAAMbmFtZRdfF18AAAE8AAAAXHBvc3QAAAAAAAEwAAAAIHN0cmQAAAAAAAEwAAAArgAB' +
    'AAAAAQAAzVp5YF8PPPUACwPoAAAAAM1aefAAAAAAzVp58AAAAAAD6APoAAAACAACAAEA' +
    'AAAAAQAAArgA/gBcAAAD6AAAAAAD6AABAAAAAAAAAAAAAAAAAAAAAwABAAAAAwAGAAIA' +
    'AAAAAAIAAAABAAEAAABAAAAAAAAAAA==';

const ROBOTO_MEDIUM_ITALIC_B64 =
    'AAEAAAASAQAABAAwR0RFRgArACgAAAEsAAAAHkdQTVNYL8SNAAABTAAAAExPUy8yYmBv' +
    'bQAAAVgAAABgY21hcAC0ALQAAAGwAAAAGGdhcHMAAAAAAAABMAAAAARnbHlmGv8a/wAA' +
    'AbAAAAAEaGVhZAF9v70AAADsAAAANmhoZWEIaQIDAAAA1AAAACRobWF4AhgAtAAAARgA' +
    'AAAMbmFtZRdfF18AAAE8AAAAXHBvc3QAAAAAAAEwAAAAIHN0cmQAAAAAAAEwAAAArgAB' +
    'AAAAAQAAzVp5YF8PPPUACwPoAAAAAM1aefAAAAAAzVp58AAAAAAD6APoAAAACAACAAEA' +
    'AAAAAQAAArgA/gBcAAAD6AAAAAAD6AABAAAAAAAAAAAAAAAAAAAAAwABAAAAAwAGAAIA' +
    'AAAAAAIAAAABAAEAAABAAAAAAAAAAA==';

// ==========================================
// B. VIRTUAL FILE SYSTEM DICTIONARY BUNDLE
// ==========================================

const vfs: Record<string, string> = {
    // 1. Times New Roman Mapping
    'times.ttf': SERIF_REGULAR_B64,
    'timesbd.ttf': SERIF_BOLD_B64,
    'timesi.ttf': SERIF_ITALIC_B64,
    'timesbi.ttf': SERIF_BOLD_ITALIC_B64,

    // 2. Calibri Mapping
    'calibri.ttf': SANS_REGULAR_B64,
    'calibrib.ttf': SANS_BOLD_B64,
    'calibrii.ttf': SANS_ITALIC_B64,
    'calibriz.ttf': SANS_BOLD_ITALIC_B64,

    // 3. Verdana Mapping
    'verdana.ttf': SANS_REGULAR_B64,
    'verdanab.ttf': SANS_BOLD_B64,
    'verdanai.ttf': SANS_ITALIC_B64,
    'verdanaz.ttf': SANS_BOLD_ITALIC_B64,

    // 4. Arial Mapping
    'arial.ttf': SANS_REGULAR_B64,
    'arialbd.ttf': SANS_BOLD_B64,
    'ariali.ttf': SANS_ITALIC_B64,
    'arialbi.ttf': SANS_BOLD_ITALIC_B64,

    // 5. Roboto Fallback Mapping (Penting: agar pdfmake tetap stabil jika ada komponen legacy menggunakan Roboto)
    'Roboto-Regular.ttf': ROBOTO_REGULAR_B64,
    'Roboto-Medium.ttf': ROBOTO_MEDIUM_B64,
    'Roboto-Italic.ttf': ROBOTO_ITALIC_B64,
    'Roboto-MediumItalic.ttf': ROBOTO_MEDIUM_ITALIC_B64,
};

export default vfs;